// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

// Project URL and anon key hardcoded in source (DEMO NOTE: both values are fake placeholders).
const SUPABASE_URL = 'https://xxxx.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.demo-anon-key.not-a-real-key';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
